<?php
// Suppress ALL error output for JSON responses - MUST be first
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
ini_set('log_errors', 1);

// Start output buffering IMMEDIATELY to catch any unexpected output
ob_start();

// Set JSON header early before any includes
header('Content-Type: application/json; charset=utf-8');

require_once dirname(__DIR__) . '/config.php';
require_once APP_PATH . '/includes/db.php';
require_once APP_PATH . '/includes/auth.php';
require_once APP_PATH . '/includes/functions.php';

// Clear any output that might have been generated by includes
ob_clean();

try {
    initSession();
    
    if (!isset($_SESSION['user_id'])) {
        ob_clean();
        echo json_encode(['success' => false, 'message' => 'Not authenticated']);
        ob_end_flush();
        exit;
    }
    
    $auth = Auth::getInstance();
    if (!$auth->hasPermission('invoices.create')) {
        ob_clean();
        echo json_encode(['success' => false, 'message' => 'Insufficient permissions']);
        ob_end_flush();
        exit;
    }
    
    $input = json_decode(file_get_contents('php://input'), true);
    if (!$input) {
        ob_clean();
        echo json_encode(['success' => false, 'message' => 'Invalid request data']);
        ob_end_flush();
        exit;
    }
    
    $db = Database::getInstance();
    
    // Check if database connection is valid
    if (!$db) {
        throw new Exception('Database connection failed');
    }
    
    $db->beginTransaction();
    
    // Generate invoice number
    $invoiceType = $input['invoice_type'] ?? 'Proforma';
    $prefix = [
        'Proforma' => 'PROF',
        'TaxInvoice' => 'TAX',
        'Quote' => 'QUO',
        'CreditNote' => 'CRN',
        'Receipt' => 'INV'
    ][$invoiceType] ?? 'INV';
    
    $datePrefix = date('Ymd');
    $maxAttempts = 10;
    $invoiceNumber = null;
    
    for ($i = 0; $i < $maxAttempts; $i++) {
        $sequence = str_pad(rand(1, 9999), 4, '0', STR_PAD_LEFT);
        $candidate = $prefix . '-' . $datePrefix . '-' . $sequence;
        
        $exists = $db->getRow("SELECT id FROM invoices WHERE invoice_number = :num", [':num' => $candidate]);
        if (!$exists) {
            $invoiceNumber = $candidate;
            break;
        }
    }
    
    if (!$invoiceNumber) {
        throw new Exception('Failed to generate unique invoice number');
    }
    
    // Validate due date - cannot be earlier than today
    $dueDate = $input['due_date'] ?? null;
    if ($dueDate) {
        $dueDateObj = new DateTime($dueDate);
        $today = new DateTime();
        $today->setTime(0, 0, 0);
        $dueDateObj->setTime(0, 0, 0);
        
        if ($dueDateObj < $today) {
            ob_clean();
            echo json_encode(['success' => false, 'message' => 'Due date cannot be earlier than today\'s date']);
            ob_end_flush();
            exit;
        }
    }
    
    // Validate branch_id is required
    $branchId = $input['branch_id'] ?: ($_SESSION['branch_id'] ?? null);
    if (!$branchId) {
        ob_clean();
        echo json_encode(['success' => false, 'message' => 'Branch is required']);
        ob_end_flush();
        exit;
    }
    
    // Format invoice_date properly (ensure it's datetime)
    $invoiceDate = $input['invoice_date'] ?? date('Y-m-d');
    if (strlen($invoiceDate) == 10) {
        // If only date provided, add time
        $invoiceDate = $invoiceDate . ' ' . date('H:i:s');
    }
    
    // Insert invoice
    $invoiceData = [
        'invoice_number' => $invoiceNumber,
        'invoice_type' => $invoiceType,
        'customer_id' => $input['customer_id'] ?: null,
        'branch_id' => $branchId,
        'user_id' => $_SESSION['user_id'],
        'subtotal' => $input['subtotal'] ?? 0,
        'discount_amount' => $input['discount_amount'] ?? 0,
        'tax_amount' => $input['tax_amount'] ?? 0,
        'total_amount' => $input['total_amount'] ?? 0,
        'balance_due' => $input['total_amount'] ?? 0,
        'invoice_date' => $invoiceDate,
        'due_date' => $dueDate,
        'status' => 'Draft', // Use 'Draft' instead of 'Pending' to match enum
        'notes' => $input['notes'] ?? null,
        'terms' => $input['terms'] ?? null,
        'terms_id' => isset($input['terms_id']) && $input['terms_id'] ? intval($input['terms_id']) : null,
        'banking_details_included' => isset($input['banking_details_included']) ? intval($input['banking_details_included']) : 1
    ];
    
    try {
        $invoiceId = $db->insert('invoices', $invoiceData);
        
        if (!$invoiceId || $invoiceId === false) {
            $error = 'Database insert failed';
            error_log("Failed to insert invoice. Invoice data: " . json_encode($invoiceData));
            throw new Exception('Failed to create invoice record');
        }
    } catch (Exception $insertError) {
        error_log("Invoice insert exception: " . $insertError->getMessage());
        throw new Exception('Failed to create invoice: ' . $insertError->getMessage());
    }
    
    // Insert invoice items
    if (!empty($input['items']) && is_array($input['items'])) {
        foreach ($input['items'] as $item) {
            // Get product name if product_id exists, otherwise use description
            $description = $item['description'] ?? '';
            if ($item['product_id']) {
                $product = $db->getRow("SELECT brand, model FROM products WHERE id = :id", [':id' => $item['product_id']]);
                if ($product) {
                    $description = trim(($product['brand'] ?? '') . ' ' . ($product['model'] ?? ''));
                }
            }
            
            $itemData = [
                'invoice_id' => $invoiceId,
                'product_id' => $item['product_id'] ?: null,
                'quantity' => $item['quantity'] ?? 1,
                'unit_price' => $item['unit_price'] ?? 0,
                'discount_percentage' => $item['discount_percentage'] ?? 0,
                'discount_amount' => ($item['quantity'] * $item['unit_price']) * ($item['discount_percentage'] / 100),
                'line_total' => $item['line_total'] ?? 0,
                'cost_price' => 0,
                'profit_margin' => 0
            ];
            
            // Add description if column exists (for manual items)
            // Check if description column exists in invoice_items table
            try {
                $columnCheck = $db->getRow("SHOW COLUMNS FROM invoice_items WHERE Field = 'description'");
                if ($columnCheck) {
                    $itemData['description'] = $description ?: null;
                }
            } catch (Exception $e) {
                // Column doesn't exist, skip - this is okay
                error_log("Description column check: " . $e->getMessage());
            }
            
            // Get product cost if product_id exists
            if ($item['product_id']) {
                $product = $db->getRow("SELECT cost_price, requires_specific_list FROM products WHERE id = :id", [':id' => $item['product_id']]);
                if ($product) {
                    $itemData['cost_price'] = $product['cost_price'] ?? 0;
                    if ($itemData['unit_price'] > 0) {
                        $itemData['profit_margin'] = (($itemData['unit_price'] - $itemData['cost_price']) / $itemData['unit_price']) * 100;
                    }
                    
                    // Handle product_specific_list entries if required
                    $requiresSpecificList = !empty($product['requires_specific_list']);
                    $specificListEntries = $item['specific_list_entries'] ?? [];
                    
                    if ($requiresSpecificList) {
                        // Validate specific list entries
                        if (empty($specificListEntries) || count($specificListEntries) !== $item['quantity']) {
                            throw new Exception("Product '{$description}' requires specific instance details for all {$item['quantity']} items.");
                        }
                    }
                }
            }
            
            try {
                $itemInsertId = $db->insert('invoice_items', $itemData);
                if (!$itemInsertId || $itemInsertId === false) {
                    error_log("Failed to insert invoice item. Item data: " . json_encode($itemData));
                    throw new Exception('Failed to create invoice item');
                }
                
                // Store specific_list_entries for products requiring specific list
                // These will be used when converting invoice to sale
                if ($requiresSpecificList && !empty($specificListEntries)) {
                    // Store as JSON in a notes field or create a separate table entry
                    // For now, we'll store it in a JSON field if available, or skip
                    // The convert to sale will handle the actual product_specific_list updates
                    try {
                        // Check if invoice_items has a notes or metadata column
                        $columnCheck = $db->getRow("SHOW COLUMNS FROM invoice_items WHERE Field IN ('notes', 'metadata', 'specific_list_data')");
                        if ($columnCheck) {
                            $db->update('invoice_items', [
                                'notes' => json_encode(['specific_list_entries' => $specificListEntries])
                            ], ['id' => $itemInsertId]);
                        }
                    } catch (Exception $e) {
                        // Column doesn't exist - we'll handle this in convert to sale
                        error_log("Could not store specific_list_entries in invoice_items: " . $e->getMessage());
                    }
                }
            } catch (Exception $itemError) {
                error_log("Invoice item insert exception: " . $itemError->getMessage());
                throw new Exception('Failed to create invoice item: ' . $itemError->getMessage());
            }
        }
    }
    
    $db->commitTransaction();
    
    // Log activity (non-critical, wrap in try-catch)
    try {
        logActivity($_SESSION['user_id'], 'invoice_created', 'Invoice created: ' . $invoiceNumber, [
            'invoice_id' => $invoiceId,
            'invoice_type' => $invoiceType
        ]);
    } catch (Exception $e) {
        // Non-critical, continue
        error_log("Failed to log invoice activity: " . $e->getMessage());
    }
    
    ob_clean();
    echo json_encode([
        'success' => true,
        'message' => 'Invoice created successfully',
        'invoice_id' => $invoiceId,
        'invoice_number' => $invoiceNumber
    ]);
    ob_end_flush();
    exit;
    
} catch (Exception $e) {
    // Ensure we're in a clean state
    if (isset($db) && $db->getPdo()->inTransaction()) {
        try {
            $db->rollbackTransaction();
        } catch (Exception $rollbackError) {
            error_log("Rollback error during invoice creation: " . $rollbackError->getMessage());
        }
    }
    
    ob_clean();
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
    ob_end_flush();
    exit;
} catch (Error $e) {
    // Handle PHP 7+ errors
    if (isset($db) && $db->getPdo()->inTransaction()) {
        try {
            $db->rollbackTransaction();
        } catch (Exception $rollbackError) {
            error_log("Rollback error during invoice creation: " . $rollbackError->getMessage());
        }
    }
    
    ob_clean();
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'An error occurred: ' . $e->getMessage()
    ]);
    ob_end_flush();
    exit;
}

